const app = require('./appImport');
const Image = require('../Models/images');
const fs = require('fs');
const multer = require('multer');
const path = require('path');


const storage = multer.diskStorage({
    destination: (req, file, cb) => {
      cb(null, './uploads/'); // make sure this folder exists
    },
    filename: (req, file, cb) => {
      cb(null, Date.now() + '-' + file.originalname);
    }
  });

  
const upload = multer({ storage });



app.post('/uploads', upload.single('image'), async (req, resp) => {
    try {
        if (!req.file) {
            return resp.status(400).send("Please upload an image file.");
        }

        const filename = req.file.filename; // Get the filename generated by multer
        const filepath = path.posix.join('./uploads/', filename); // Construct the relative filepath

        let data = new Image({
            filename: filename,
            filepath: filepath
        });

        let result = await data.save();

        if (result) {
            console.log("Image details saved to database:", result);
            resp.send(result.id);
        } else {
            resp.status(500).send("Error saving image details to the database.");
        }
    } catch (error) {
        console.error("Error during image upload and database save:", error);
        resp.status(500).send("Server error during upload.");
    }
});


app.get('/image' , async (req , resp) => {
    let data = await Images.find();
    if(data){
        console.log("found");
        resp.send(data);
    }else{
        resp.status(400).send("error");
    }
})


// app.get('/image/:id' , async (req , resp) =>{
//     try{

//         let data = await Image.findById(req.params._id);

//     if(!data){
//         return resp.status(404).send("Image Not found");
//     }

//     const fullPath = path.join(__dirname, data.filepath); // Use the stored relative path

//     if(!fs.existsSync(fullPath)){
//         return resp.status(404).send("Image Not found");
//     }

//     const ext = path.extname(data.filename).toLowerCase();
//     const imageTypes = {
//         '.jpg' : 'image/jpeg',
//         '.jpeg' : 'image/jpeg',
//         '.png' : 'image/png',
//     };

//     resp.setHeader('Content-Type' , imageTypes[ext] || 'application/octet-stream');

//     const readStream = fs.createReadStream(fullPath);
//     readStream.pipe(resp);

//     } catch (err) {
//         resp.status(500).send("error");
//     }
// });

